import os

path = r'c:\Users\uveys\OneDrive\Masaüstü\ProjeMoffi1\MoffiVercel\src\components\community\HubOverlay.tsx'
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the line where "return (" starts for the main component
start_idx = -1
for i, line in enumerate(lines):
    if 'return (' in line and i > 100: 
        start_idx = i
        break

if start_idx != -1:
    new_return = [
        "    return (\n",
        "        <AnimatePresence>\n",
        "            {isOpen && (\n",
        "                <motion.div\n",
        "                    initial={{ opacity: 0, y: 30 }}\n",
        "                    animate={{ opacity: 1, y: 0 }}\n",
        "                    exit={{ opacity: 0, y: 30 }}\n",
        "                    transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}\n",
        "                    className=\"fixed inset-0 h-[100dvh] w-screen z-[2000] backdrop-blur-3xl flex flex-col overflow-hidden\"\n",
        "                    style={{ background: 'var(--background)' }}\n",
        "                >\n",
        "                    {/* MOFFI PRO STICKY HEADER */}\n",
        "                    <div className=\"pt-safe px-6 pb-4 border-b border-white/5 bg-background/80 backdrop-blur-xl z-[2001]\">\n",
        "                        <div className=\"flex justify-between items-center py-4\">\n",
        "                            <div>\n",
        "                                <div className=\"flex items-center gap-2 mb-0.5\">\n",
        "                                    <span className=\"w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse\" />\n",
        "                                    <p className=\"text-[9px] font-black text-emerald-500 uppercase tracking-[0.3em]\">Moffi Pro Hub</p>\n",
        "                                </div>\n",
        "                                <h2 className=\"text-2xl font-black text-foreground uppercase italic tracking-tighter leading-none\">Control Center</h2>\n",
        "                            </div>\n",
        "                            <div className=\"flex gap-2.5\">\n",
        "                                <button \n",
        "                                    onClick={() => { onAIAsistantClick?.(); onClose(); }}\n",
        "                                    className=\"h-10 w-10 rounded-xl bg-purple-500/20 text-purple-400 flex items-center justify-center border border-purple-500/20 active:scale-95 transition-all\"\n",
        "                                >\n",
        "                                    <Sparkles size={18} />\n",
        "                                </button>\n",
        "                                <button \n",
        "                                    onClick={onClose}\n",
        "                                    className=\"w-10 h-10 rounded-xl bg-foreground/5 text-foreground flex items-center justify-center border border-white/10 active:scale-95 transition-all\"\n",
        "                                >\n",
        "                                    <X size={20} />\n",
        "                                </button>\n",
        "                            </div>\n",
        "                        </div>\n",
        "                        \n",
        "                        <div className=\"flex justify-between items-end mt-1\">\n",
        "                            <button \n",
        "                                onClick={() => alert(\"Vet-Line 7/24 Canlı Destek Başlatılıyor...\")}\n",
        "                                className=\"h-10 px-4 rounded-xl bg-indigo-500 text-white flex items-center gap-2 text-[9px] font-black uppercase tracking-widest shadow-lg shadow-indigo-500/20 active:scale-95 transition-all\"\n",
        "                            >\n",
        "                                <PhoneCall size={14} />\n",
        "                                <span>Vet-Line</span>\n",
        "                            </button>\n",
        "                            <div className=\"text-right\">\n",
        "                                <p className=\"text-3xl font-black text-foreground italic tracking-tighter leading-none\">{currentTime}</p>\n",
        "                                <p className=\"text-[8px] font-bold text-gray-500 uppercase tracking-widest mt-1\">Sistem Aktif • TR</p>\n",
        "                            </div>\n",
        "                        </div>\n",
        "                    </div>\n",
        "\n",
        "                    {/* MOFFI PRO SCROLLABLE BODY */}\n",
        "                    <div className=\"flex-1 overflow-y-auto overscroll-contain no-scrollbar px-6 pb-32 pt-6\">\n",
        "                        <div className=\"w-full max-w-full mx-auto space-y-8\">\n",
        "                            <div className=\"grid grid-cols-2 gap-4\">\n",
        "                                <div className=\"bg-[var(--card-bg)] border border-[var(--card-border)] rounded-[2rem] p-6 relative overflow-hidden\">\n",
        "                                    <div className=\"flex items-center gap-3 mb-4\">\n",
        "                                        <div className=\"w-8 h-8 rounded-full bg-cyan-500/20 flex items-center justify-center text-cyan-400\">\n",
        "                                            <Radar size={16} />\n",
        "                                        </div>\n",
        "                                        <span className=\"text-[9px] font-black text-gray-500 uppercase tracking-widest\">Pati Radarı</span>\n",
        "                                    </div>\n",
        "                                    <div className=\"flex items-baseline gap-2\">\n",
        "                                        <span className=\"text-4xl font-black text-foreground italic\">12</span>\n",
        "                                        <span className=\"text-xs text-cyan-400 font-bold uppercase italic\">Arkadaş</span>\n",
        "                                    </div>\n",
        "                                    <p className=\"text-[8px] text-gray-500 font-bold uppercase mt-2\">Çevrende Aktif</p>\n",
        "                                </div>\n",
        "                                <div className=\"bg-[var(--card-bg)] border border-[var(--card-border)] rounded-[2rem] p-6 relative overflow-hidden\">\n",
        "                                    <div className=\"flex items-center gap-3 mb-4\">\n",
        "                                        <div className=\"w-8 h-8 rounded-full bg-red-500/20 flex items-center justify-center text-red-400\">\n",
        "                                            <Activity size={16} />\n",
        "                                        </div>\n",
        "                                        <span className=\"text-[9px] font-black text-gray-500 uppercase tracking-widest\">Kritik Görev</span>\n",
        "                                    </div>\n",
        "                                    <div className=\"flex flex-col\">\n",
        "                                        <span className=\"text-xl font-black text-foreground italic uppercase leading-none truncate\">Karma Aşı II</span>\n",
        "                                        <span className=\"text-xs text-red-400 font-bold uppercase italic mt-1\">3 GÜN KALDI</span>\n",
        "                                    </div>\n",
        "                                </div>\n",
        "                            </div>\n",
        "\n",
        "                            {activeOrder && (\n",
        "                                <motion.div \n",
        "                                    initial={{ opacity: 0, y: 10 }}\n",
        "                                    animate={{ opacity: 1, y: 0 }}\n",
        "                                    className=\"bg-gradient-to-br from-orange-500/10 to-transparent border border-orange-500/20 rounded-[2.5rem] p-6\"\n",
        "                                >\n",
        "                                    <div className=\"flex items-center justify-between\">\n",
        "                                        <div className=\"flex items-center gap-4\">\n",
        "                                            <div className=\"w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center text-white shadow-lg shadow-orange-500/20\">\n",
        "                                                <Truck size=\"20\" />\n",
        "                                            </div>\n",
        "                                            <div>\n",
        "                                                <h4 className=\"text-base font-black text-white italic tracking-tight uppercase leading-none\">Moffi Express ⚡️</h4>\n",
        "                                                <p className=\"text-[8px] text-orange-400 font-bold uppercase tracking-widest mt-1\">Paket Yolda • 8dk</p>\n",
        "                                            </div>\n",
        "                                        </div>\n",
        "                                        <div className=\"text-right\">\n",
        "                                            <p className=\"text-xl font-black text-white italic tracking-tighter\">1.4 km</p>\n",
        "                                        </div>\n",
        "                                    </div>\n",
        "                                </motion.div>\n",
        "                            )}\n",
        "\n",
        "                            <div>\n",
        "                                <div className=\"flex items-center justify-between mb-4 px-2\">\n",
        "                                    <h3 className=\"text-[10px] font-black text-gray-500 uppercase tracking-widest\">Hızlı Sepet</h3>\n",
        "                                    <button onClick={onMarketClick} className=\"text-[9px] font-black text-orange-400 uppercase tracking-widest\">Market</button>\n",
        "                                </div>\n",
        "                                <div className=\"flex gap-4 overflow-x-auto no-scrollbar px-1\">\n",
        "                                    {fastBasket.map((item) => (\n",
        "                                        <div key={item.id} className=\"min-w-[130px] bg-foreground/5 border border-white/5 rounded-[2rem] p-4 flex flex-col gap-3\">\n",
        "                                            <div className=\"w-full aspect-square rounded-2xl overflow-hidden relative\">\n",
        "                                                <img src={item.img} alt={item.name} className=\"w-full h-full object-cover\" />\n",
        "                                                <button className=\"absolute bottom-2 right-2 w-7 h-7 rounded-full bg-emerald-500 text-white flex items-center justify-center shadow-lg\"><ShoppingCart size={12} /></button>\n",
        "                                            </div>\n",
        "                                            <div className=\"text-left px-1\">\n",
        "                                                <p className=\"text-[9px] font-black text-foreground leading-tight uppercase truncate\">{item.name}</p>\n",
        "                                                <p className=\"text-[10px] font-black text-orange-400 mt-1 italic\">{item.price}</p>\n",
        "                                            </div>\n",
        "                                        </div>\n",
        "                                    ))}\n",
        "                                </div>\n",
        "                            </div>\n",
        "\n",
        "                            <div className=\"grid grid-cols-2 gap-4\">\n",
        "                                <button onClick={() => { onSOSClick(); onClose(); }} className=\"bg-red-500/10 border border-red-500/20 rounded-[2rem] p-6 flex flex-col items-start gap-3 active:scale-95 transition-all\">\n",
        "                                    <div className=\"w-10 h-10 rounded-xl bg-red-500 flex items-center justify-center text-white\"><ShieldAlert size={20} /></div>\n",
        "                                    <div className=\"text-left\">\n",
        "                                        <h3 className=\"text-xs font-black text-white uppercase tracking-wider\">ACİL DURUM</h3>\n",
        "                                        <p className=\"text-[9px] text-red-500/70 font-bold uppercase mt-0.5\">SOS Gönder</p>\n",
        "                                    </div>\n",
        "                                </button>\n",
        "                                <button onClick={() => { onCommunityRadarClick(); onClose(); }} className=\"bg-cyan-500/10 border border-cyan-500/20 rounded-[2rem] p-6 flex flex-col items-start gap-3 active:scale-95 transition-all\">\n",
        "                                    <div className=\"w-10 h-10 rounded-xl bg-cyan-500 flex items-center justify-center text-white\"><Radar size={20} /></div>\n",
        "                                    <div className=\"text-left\">\n",
        "                                        <h3 className=\"text-xs font-black text-white uppercase tracking-wider\">RADAR</h3>\n",
        "                                        <p className=\"text-[9px] text-cyan-500/70 font-bold uppercase mt-0.5\">Pati Radarı</p>\n",
        "                                    </div>\n",
        "                                </button>\n",
        "                            </div>\n",
        "\n",
        "                            <div className=\"space-y-4 px-1\">\n",
        "                                <h3 className=\"text-[10px] font-black text-gray-500 uppercase tracking-widest px-1\">Yakın Klinikler</h3>\n",
        "                                {nearbyClinics.map((clinic, i) => (\n",
        "                                    <button key={i} onClick={() => { onVetClick(); onClose(); }} className=\"w-full bg-foreground/5 border border-white/5 rounded-[2rem] p-5 flex items-center justify-between active:scale-[0.98] transition-all\">\n",
        "                                        <div className=\"flex items-center gap-4 text-left\">\n",
        "                                            <div className=\"w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400\"><MapPin size={18} /></div>\n",
        "                                            <div>\n",
        "                                                <h4 className=\"text-sm font-black text-foreground italic uppercase leading-none\">{clinic.name}</h4>\n",
        "                                                <p className=\"text-[9px] text-emerald-400 font-bold uppercase mt-1\">{clinic.status}</p>\n",
        "                                            </div>\n",
        "                                        </div>\n",
        "                                        <span className=\"text-lg font-black text-foreground italic\">{clinic.dist}</span>\n",
        "                                    </button>\n",
        "                                ))}\n",
        "                            </div>\n",
        "\n",
        "                            <div className=\"space-y-4\">\n",
        "                                <h3 className=\"text-[10px] font-black text-gray-500 uppercase tracking-widest text-center\">Marketler & Servisler</h3>\n",
        "                                <div className=\"grid grid-cols-3 gap-4\">\n",
        "                                    {marketCategories.map((service, i) => (\n",
        "                                        <button key={i} onClick={() => { service.onClick(); onClose(); }} className=\"flex flex-col items-center gap-2\">\n",
        "                                            <div className={cn(\"w-14 h-14 rounded-[1.5rem] flex items-center justify-center active:scale-90 transition-all border\", service.bg)}>\n",
        "                                                <service.icon className={cn(\"w-6 h-6\", service.color)} />\n",
        "                                            </div>\n",
        "                                            <span className=\"text-[9px] font-black text-gray-500 uppercase tracking-tight text-center\">{service.label}</span>\n",
        "                                        </button>\n",
        "                                    ))}\n",
        "                                </div>\n",
        "                            </div>\n",
        "\n",
        "                            <div className=\"pt-4 pb-12\">\n",
        "                                <div className=\"bg-white/[0.03] border border-white/5 rounded-[2.5rem] p-6\">\n",
        "                                    <div className=\"grid grid-cols-3 gap-6\">\n",
        "                                        {[\n",
        "                                            { icon: Palette, label: 'Stüdyo', color: 'text-purple-400', bg: 'bg-purple-500/10', onClick: onStudioClick },\n",
        "                                            { icon: Gamepad2, label: 'Oyun', color: 'text-indigo-400', bg: 'bg-indigo-500/10', onClick: onGameClick },\n",
        "                                            { icon: PawPrint, label: 'Yürüyüş', color: 'text-emerald-400', bg: 'bg-emerald-500/10', onClick: onWalkClick },\n",
        "                                        ].map((service, i) => (\n",
        "                                            <button key={i} onClick={() => { service.onClick(); onClose(); }} className=\"flex flex-col items-center gap-2.5 active:scale-95 transition-all\">\n",
        "                                                <div className={cn(\"w-14 h-14 rounded-[1.5rem] flex items-center justify-center border border-white/5 shadow-lg shadow-black/20\", service.bg)}>\n",
        "                                                    <service.icon className={cn(\"w-6 h-6\", service.color)} />\n",
        "                                                </div>\n",
        "                                                <span className=\"text-[10px] font-black text-gray-500 uppercase tracking-widest\">{service.label}</span>\n",
        "                                            </button>\n",
        "                                        ))}\n",
        "                                    </div>\n",
        "                                </div>\n",
        "                            </div>\n",
        "                        </div>\n",
        "                    </div>\n",
        "                </motion.div>\n",
        "            )}\n",
        "        </AnimatePresence>\n",
        "    );\n",
        "}\n"
    ]
    
    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(lines[:start_idx] + new_return)
