-- Görev Merkezi içerik: programlar (çok günlü, öğretici). Günde bir adım; sırayla.
-- 🔴 vet_reviewed = false: herkese açık yayından önce bir veterinerin okuması gerekir (CLAUDE.md 12.1).

insert into public.badge_defs (key, family, tier, title, description, icon, category, metric, threshold, unit, pawcoin, xp, hidden, sort) values
('prog_yavru', 'program', 1, 'Yavru Maceracı', '"Yavru Köpeğin 30 Günü" programını bitirdin', '🐾', 'egitim', 'program:yavru-kopek-30', 1, '', 0, 0, false, 70),
('prog_saglikli', 'program', 1, 'Sağlıklı Pati', '"Sağlıklı Pati" programını bitirdin', '🥗', 'saglik', 'program:saglikli-pati', 1, '', 0, 0, false, 71),
('prog_birlikte', 'program', 1, 'Mutlu Birlikte', '"Mutlu Birlikte" programını bitirdin', '💞', 'sosyal', 'program:mutlu-birlikte', 1, '', 0, 0, false, 72),
('prog_yeni_ev', 'program', 1, 'Yeni Ev', '"Yeni Ev" programını bitirdin', '🏡', 'ozel', 'program:yeni-ev', 1, '', 0, 0, false, 73),
('prog_kedi', 'program', 1, 'Kedi Dostu', '"Mutlu Kedi Evi" programını bitirdin', '🐈', 'egitim', 'program:mutlu-kedi-evi', 1, '', 0, 0, false, 74)
on conflict (key) do update set title = excluded.title, description = excluded.description, icon = excluded.icon, category = excluded.category,
    metric = excluded.metric, sort = excluded.sort;

insert into public.programs (key, title, subtitle, description, species, tags, emoji, tint, badge_key, pawcoin, xp, sort, steps)
select x.key, x.title, x.subtitle, x.description, x.species, x.tags, x.emoji, x.tint, x.badge_key, x.pawcoin, x.xp, x.sort, x.steps
from jsonb_to_recordset($j$[
{"key":"yavru-kopek-30","sort":1,"species":["dog"],"tags":["egitim","yeni"],"emoji":"🐶","tint":"#FCE6DF","badge_key":"prog_yavru","pawcoin":200,"xp":600,
 "title":"Yavru Köpeğin 30 Günü","subtitle":"Yeni sahiplenenler için adım adım rehber",
 "description":"Ev düzeni, tuvalet eğitimi, sosyalleşme, temel komutlar ve sağlık takvimi. Günde 5–10 dakika.",
 "steps":[
  {"title":"Güvenli bir köşe","body":"Yavruya yatağı, su kabı ve birkaç oyuncağı olan sakin bir köşe hazırla. İlk günlerde evi yavaş yavaş keşfetmesine izin ver.","tip":"Kablo, ilaç ve küçük eşyaları yerden kaldır."},
  {"title":"Rutin kur","body":"Mama, tuvalet ve uyku saatlerini belirle ve her gün aynı tut. Yavrular rutinle daha çabuk güven kazanır."},
  {"title":"Tuvalet eğitimi başlıyor","body":"Uyandıktan, yemekten ve oyundan hemen sonra yavruyu aynı tuvalet noktasına götür. Doğru yere yaptığında hemen ödüllendir.","tip":"Kazaları cezalandırma; kokuyu enzimli temizleyiciyle gider."},
  {"title":"İsmini öğret","body":"İsmini söyle, sana baktığı anda küçük bir ödül ver. Günde birkaç kez kısa tekrarlar yeterli."},
  {"title":"Veteriner kontrolü","body":"İlk kontrol için randevu planla. Aşı takvimini, parazit korumasını ve mikroçip kaydını konuş."},
  {"title":"Kafes ya da yatak alışkanlığı","body":"Yatağını ya da kafesini güvenli bir yer haline getir: içine ödül ve oyuncak bırak, kapıyı kısa sürelerle kapat."},
  {"title":"Dokunmaya alıştır","body":"Patilerine, kulaklarına ve ağzına nazikçe dokun, her dokunuşu bir ödülle eşleştir. Veteriner ve bakım ziyaretlerini kolaylaştırır."},
  {"title":"'Otur' komutu","body":"Ödülü burnunun önünden başının üzerine doğru yavaşça kaldır; poposu yere değdiğinde 'otur' de ve ödül ver."},
  {"title":"Isırma terbiyesi","body":"Oyunda dişlerini fazla kullanırsa oyunu birkaç saniye durdur. Isırmak için ona uygun çiğneme oyuncakları sun."},
  {"title":"Yeni sesler","body":"Süpürge, kapı zili, trafik gibi sesleri düşük seviyede ve ödülle tanıştır. Korkarsa mesafeyi artır."},
  {"title":"Tasma ve koşum","body":"Evde koşumu birkaç dakika taktır, oyunla eşleştir. Tasmaya bağlıyken kısa ev içi yürüyüşler yap."},
  {"title":"Yalnız kalmayı öğret","body":"Birkaç dakikalık ayrılıklarla başla, çıkış ve dönüşleri sakin tut. Süreyi yavaş yavaş uzat."},
  {"title":"Yeni insanlar","body":"Sakin bir arkadaşının yavruyu ödülle karşılamasını iste. Yavrunun kendisinin yaklaşmasına izin ver."},
  {"title":"'Gel' komutu","body":"Yakın mesafeden ismini söyle, geldiğinde büyük bir ödül ver. Bu komut ileride hayat kurtarabilir."},
  {"title":"Kucakta şehir turu","body":"Aşıları tamamlanmadıysa kucakta ya da arabada kısa gezilerle yeni görüntüler ve kokular sun."},
  {"title":"Diş fırçalamaya giriş","body":"Parmağına köpeklere özel diş macunundan biraz alıp tattır. Birkaç gün içinde diş etine dokunmaya geç."},
  {"title":"Farklı zeminler","body":"Halı, fayans, çim, ızgara gibi farklı yüzeylerde yürümesini ödülle teşvik et."},
  {"title":"'Bekle' komutu","body":"Otururken avucunu göster, bir iki saniye beklediğinde ödül ver. Süreyi saniye saniye artır."},
  {"title":"Mama kabı nezaketi","body":"Mama kabını yere koymadan önce oturmasını bekle. Yemek yerken onu rahatsız etme; güven kazanır."},
  {"title":"Aşılı bir arkadaş","body":"Aşıları tam, sakin bir yetişkin köpekle kontrollü bir tanışma ayarla. Kısa tut ve iyi bitir."},
  {"title":"İlk dış yürüyüşler","body":"Veterinerin onay verdiyse kısa ve sakin yürüyüşlere başla. Koklamasına izin ver; mesafe değil deneyim önemli."},
  {"title":"Tasmayı çekmeden yürüme","body":"Tasma gerildiğinde dur, gevşediğinde devam et. Yanında yürüdüğünde ödül ver."},
  {"title":"'Bırak' komutu","body":"Elindeki ödülü yumruğunda tut; ilgisini çektiğinde 'bırak' de, bıraktığında diğer elinden ödül ver."},
  {"title":"Araba yolculuğu","body":"Kısa ve keyifli bir araba yolculuğu yap; varış noktası veteriner değil, sevdiği bir yer olsun."},
  {"title":"Tımar zamanı","body":"Kısa bir tarama seansı yap ve tüylerini, derisini kontrol et."},
  {"title":"Koklama oyunu","body":"Ödülleri bir havlunun kıvrımlarına sakla, bulmasına izin ver. Zihinsel yorgunluk da uyku getirir."},
  {"title":"Tekrar günü","body":"Otur, bekle, gel ve bırak komutlarını kısa ve eğlenceli bir seansla tekrar et."},
  {"title":"Kilo ve gelişim","body":"Yavrunu tart ve kaydet. Büyüme hızını veterinerinin önerileriyle karşılaştır."},
  {"title":"Aşı ve parazit takvimi","body":"Moffi'de aşı ve parazit kayıtlarının güncel olduğundan emin ol; sıradaki tarihleri kontrol et."},
  {"title":"Mezuniyet","body":"30 günü tamamladın! Yavrunun öğrendiklerini bir video ya da fotoğrafla kutla ve topluluğunla paylaş."}]},
{"key":"saglikli-pati","sort":2,"species":null,"tags":["saglik"],"emoji":"🥗","tint":"#DFF3EA","badge_key":"prog_saglikli","pawcoin":150,"xp":500,
 "title":"Sağlıklı Pati","subtitle":"Beslenme, su ve günlük bakım",
 "description":"30 günde sağlıklı alışkanlıklar: doğru porsiyon, taze su, diş, tüy ve tırnak bakımı, kilo takibi.",
 "steps":[
  {"title":"Başlangıç tartısı","body":"Hayvanını tart ve Moffi'ye kaydet. Bu, 30 günün başlangıç noktası olacak."},
  {"title":"Vücut kondisyonu","body":"Kaburgalarını eline al: ince bir tabakanın altında kolayca hissedilmeli. Yukarıdan bakınca bel çizgisi görünmeli."},
  {"title":"Porsiyonu ölç","body":"Mamayı göz kararı değil, ölçü kabı ya da tartıyla ver. Günlük miktarı veterinerinin önerisine göre ayarla."},
  {"title":"Su noktaları","body":"Evde en az iki farklı noktaya taze su koy; kapları her gün yıka."},
  {"title":"Öğün saatleri","body":"Öğünleri her gün aynı saatlerde ver ve Moffi'de işaretle. İştahtaki değişimleri erken fark edersin."},
  {"title":"Ödülleri say","body":"Gün içinde verdiğin ödülleri say; günlük kalorinin onda birini geçmemeli."},
  {"title":"Diş kontrolü","body":"Ağzına bak: diş taşı, kızarık diş eti ya da kötü koku var mı? Not al."},
  {"title":"İlk fırçalama","body":"Hayvanlara özel diş macunuyla kısa bir fırçalama dene. 30 saniye yeterli."},
  {"title":"Tüy kontrolü","body":"Tara ve deriyi kontrol et: kepek, kızarıklık ya da pire var mı?"},
  {"title":"Hareket planı","body":"Hayvanının yaşına uygun günlük hareket hedefini belirle: köpekler için yürüyüş, kediler için oyun."},
  {"title":"Tırnak kontrolü","body":"Tırnaklar yere tıkırdıyorsa kesim zamanı gelmiş demektir. Gerekirse küçük parçalar halinde kes."},
  {"title":"Kulak kontrolü","body":"Kulakların içine bak; koyu kir, koku ya da sürekli kaşıma veterinere gitme işaretidir."},
  {"title":"Göz kontrolü","body":"Gözler parlak ve akıntısız olmalı. Kızarıklık ya da sürekli sulanma varsa not al."},
  {"title":"Ara tartı","body":"İkinci tartıyı yap ve kaydet. İlk tartıyla karşılaştır."},
  {"title":"Mama etiketini oku","body":"Mamanın içeriğine ve hangi yaş grubuna uygun olduğuna bak. Sorun varsa veterinerinle konuş."},
  {"title":"Zehirli yiyecekler","body":"Evdeki tehlikeli yiyecekleri ve bitkileri gözden geçir; ulaşabileceği yerlerden kaldır."},
  {"title":"Parazit takvimi","body":"Son iç ve dış parazit uygulamasının tarihini kontrol et; gerekiyorsa sıradakini planla."},
  {"title":"Diş fırçalama alışkanlığı","body":"Bugün yine kısa bir fırçalama yap. Her gün 30 saniye, haftada bir uzun seanstan daha etkilidir."},
  {"title":"Zihinsel egzersiz","body":"Mamanın bir kısmını bulmaca oyuncağıyla ya da saklayarak ver."},
  {"title":"Su tüketimini izle","body":"Bugün kabı kaç kez doldurduğunu not et. Ani değişimleri bilmek için iyi bir referans olur."},
  {"title":"Aşı kontrolü","body":"Aşı kartını Moffi'deki kayıtlarla karşılaştır; eksik varsa ekle."},
  {"title":"Tüy dökme mevsimi","body":"Tarama sıklığını artır; tüy yumağı ve keçelenme oluşumunu önler."},
  {"title":"Üçüncü tartı","body":"Tart ve kaydet. Hedef kiloda mısınız, yoksa porsiyonu ayarlamak mı gerekiyor?"},
  {"title":"Acil durum bilgisi","body":"Moffi'de acil durum kişisini ve veteriner bilgisini doldur."},
  {"title":"Yaşa uygun bakım","body":"Hayvanının yaşına göre (yavru, yetişkin, yaşlı) bakım önerilerini oku."},
  {"title":"Dinlenme alanı","body":"Yatağını temizle, sessiz ve cereyansız bir yerde olduğundan emin ol."},
  {"title":"Ek kontrol listesi","body":"Patiler, kulaklar, gözler ve dişleri bir kez daha kontrol et; değişenleri not al."},
  {"title":"Sağlık soruları","body":"Bir sonraki veteriner ziyaretinde sormak istediklerini Moffi'deki notlara yaz."},
  {"title":"Son tartı","body":"30 günün son tartısını yap ve başlangıçla karşılaştır."},
  {"title":"Tebrikler","body":"30 günlük sağlıklı alışkanlıkları tamamladın! Bunları sürdürmek için günlük görevler seni bekliyor."}]},
{"key":"mutlu-birlikte","sort":3,"species":null,"tags":["sosyal"],"emoji":"💞","tint":"#F9E1E8","badge_key":"prog_birlikte","pawcoin":150,"xp":450,
 "title":"Mutlu Birlikte","subtitle":"Bağınızı güçlendiren 21 gün",
 "description":"Birlikte oyun, keşif, arkadaş görevleri ve topluluk. Hem hayvanınla hem diğer sahiplerle bağ kur.",
 "steps":[
  {"title":"Kaliteli zaman","body":"Bugün telefonsuz 10 dakika ayır: sadece onunla oyna ya da yanında otur."},
  {"title":"Sevdiği şeyler","body":"En sevdiği oyuncak, ödül ve sevilme şeklini bir listeye yaz. Ödül olarak bunları kullanacaksın."},
  {"title":"Yeni bir oyun","body":"Daha önce oynamadığınız bir oyun dene: saklambaç, ip çekme ya da olta oyuncağı."},
  {"title":"Beden dili","body":"Bugün mutlu, rahat ve gergin olduğu anlardaki beden dilini gözlemle."},
  {"title":"Birlikte keşif","body":"Köpeğinle yeni bir rota yürü; kedinle evde yeni bir köşe keşfet."},
  {"title":"Bir numara öğret","body":"Basit bir numara seç: pati ver, dön ya da 'beşlik'. Kısa seanslarla çalış."},
  {"title":"Fotoğraf günü","body":"Güzel bir anınızı fotoğrafla ve albüme ekle."},
  {"title":"Topluluğa merhaba","body":"Keşfet'te hayvanını etiketleyerek bir anı paylaş."},
  {"title":"Arkadaşını davet et","body":"Hayvan sahibi bir arkadaşını Moffi'ye davet et ya da takipleş."},
  {"title":"Ortak hedef","body":"Bir arkadaşınla Birlikte bölümünden haftalık ortak hedef oluştur."},
  {"title":"Koklama ya da avcılık","body":"Köpeğinle koklama yürüyüşü yap; kedinle av oyunu oyna."},
  {"title":"Masaj ve dokunuş","body":"Sevdiği yerlerden nazikçe sev; rahatlamış bir hayvan güvenini gösterir."},
  {"title":"Numara tekrarı","body":"Öğrendiği numarayı farklı bir odada tekrar et."},
  {"title":"Birlikte dinlen","body":"Bugün acelesiz bir gün: kısa yürüyüş ya da oyun, sonra birlikte dinlenme."},
  {"title":"Yeni bir kişiyle tanış","body":"Sakin bir arkadaşın ödülle tanışsın; hayvanın yaklaşmayı kendi seçsin."},
  {"title":"Topluluğa destek","body":"Yakınındaki kayıp ve sahiplendirme ilanlarına göz at; bir ilanı paylaşmak bir hayvanın yuvasına dönmesini sağlayabilir."},
  {"title":"Ortak hedefi kontrol et","body":"Arkadaşlarınla hedefinizde nerede olduğunuza bak; bir motivasyon mesajı gönder."},
  {"title":"Oyun icat et","body":"Evdeki malzemelerle yeni bir oyun icat et: kartondan tünel ya da bardak altında ödül bulma."},
  {"title":"Teşekkür günü","body":"Bugün ona en sevdiği ödülü ver ve birlikte en sevdiği şeyi yapın."},
  {"title":"Anı albümü","body":"Bu 21 günde çektiğin fotoğraflardan birini anı olarak kaydet."},
  {"title":"Birlikte mutlu","body":"21 günü tamamladınız! Bağınızı güçlendiren bu alışkanlıkları sürdürmeye devam et."}]},
{"key":"yeni-ev","sort":4,"species":null,"tags":["yeni"],"emoji":"🏡","tint":"#F3EBDD","badge_key":"prog_yeni_ev","pawcoin":100,"xp":350,
 "title":"Yeni Ev","subtitle":"Taşınma ve yeni ortama alışma",
 "description":"Yeni sahiplendiysen ya da taşındıysan, ilk 14 günde güvenli ve sakin bir geçiş için adımlar.",
 "steps":[
  {"title":"Güvenli oda","body":"Yatağı, suyu, maması ve kedi için kum kabı olan sakin bir oda hazırla. İlk günler burada geçsin."},
  {"title":"Evi güvenli hale getir","body":"Kabloları topla, pencerelere güvenlik önlemi al, zehirli bitkileri ve ilaçları kaldır."},
  {"title":"Tanıdık koku","body":"Eski evden ya da barınaktan gelen bir battaniye veya oyuncağı yatağına koy."},
  {"title":"Rutin","body":"Mama, oyun ve uyku saatlerini belirle; her gün aynı saatlerde tekrarla."},
  {"title":"Keşfe izin ver","body":"Hazır olduğunda evin diğer bölümlerini kendi hızında keşfetsin; zorlama."},
  {"title":"Künye ve çip","body":"Künyeye yeni adres ve telefonu ekle; çip kaydındaki bilgileri güncelle."},
  {"title":"Veteriner seç","body":"Yeni evine yakın bir veteriner kliniği belirle ve ilk kontrol için randevu planla."},
  {"title":"Diğer hayvanlarla tanışma","body":"Evde başka hayvan varsa önce koku ile tanıştır: yatak değiş tokuşu yap, sonra kapı arkasından kısa görüşmeler."},
  {"title":"Mahalleyi tanı","body":"Köpeğinle kısa yürüyüşlerle mahalleyi keşfet; kedinle pencereden manzarayı birlikte izle."},
  {"title":"Yalnız kalma","body":"Kısa ayrılıklarla başla; çıkış ve dönüşleri sakin tut."},
  {"title":"İştah ve tuvalet","body":"Yeme, içme ve tuvalet alışkanlıklarını gözlemle. Üç günü geçen iştahsızlıkta veterinere danış."},
  {"title":"Saklanma yerleri","body":"Kediler için yüksek ve kapalı saklanma yerleri, köpekler için sakin bir köşe ekle."},
  {"title":"Komşular ve sesler","body":"Yeni seslere ödülle alışmasını sağla: asansör, kapı, trafik."},
  {"title":"Hoş geldin","body":"14 günü tamamladınız! Yeni yuvanızda mutlu günler."}]},
{"key":"mutlu-kedi-evi","sort":5,"species":["cat"],"tags":["egitim","saglik"],"emoji":"🐈","tint":"#FCE6DF","badge_key":"prog_kedi","pawcoin":100,"xp":350,
 "title":"Mutlu Kedi Evi","subtitle":"Kedinin ihtiyaçlarını 14 günde öğren",
 "description":"Kum kabı düzeni, tırmalama, oyun, su tüketimi ve stres işaretleri. Ev kedisi için zengin bir yaşam.",
 "steps":[
  {"title":"Kaynakları say","body":"Mama, su, kum kabı, tırmalama ve dinlenme yerlerini listele. Her kedi için ayrı kaynak olmalı."},
  {"title":"Kum kabı düzeni","body":"Kedi sayısının bir fazlası kadar kum kabı; sessiz yerler ve günlük temizlik."},
  {"title":"Su noktaları","body":"Mama kabından uzak, geniş ve sığ su kapları koy; çeşme dene."},
  {"title":"Tırmalama yeri","body":"Uyku yerinin yakınına sağlam bir tırmalama tahtası koy, kullandığında ödül ver."},
  {"title":"Av oyunu","body":"Olta oyuncağıyla 10 dakika av oyunu oyna ve yakalama ile bitir."},
  {"title":"Yükseklik","body":"Raf ya da kedi ağacıyla dikey alan oluştur; kediler yüksekte güvende hisseder."},
  {"title":"Saklanma yerleri","body":"Karton kutu ya da kapalı yatakla saklanabileceği yerler ekle."},
  {"title":"Mama bulmacası","body":"Mamanın bir kısmını bulmaca oyuncağıyla ver; doğal arama davranışını destekler."},
  {"title":"Stres işaretleri","body":"Saklanma, aşırı yalanma ya da kum kabı değişikliği gibi işaretleri gözlemle."},
  {"title":"Tüy ve diş","body":"Kısa bir tarama ve diş kontrolü yap; değişiklikleri not al."},
  {"title":"Pencere keyfi","body":"Pencere önüne bir minder koy; dışarıyı izlemek kediler için eğlencedir."},
  {"title":"Zehirli bitkiler","body":"Evdeki bitkileri kontrol et; zambakları hemen çıkar."},
  {"title":"Oyuncak rotasyonu","body":"Oyuncakların yarısını kaldır; birkaç gün sonra değiştir, her seferinde yeni gibi gelir."},
  {"title":"Mutlu kedi","body":"14 günü tamamladın! Kedinin ihtiyaçlarını artık çok daha iyi tanıyorsun."}]}
]$j$::jsonb) as x(key text, title text, subtitle text, description text, species text[], tags text[], emoji text, tint text,
                  badge_key text, pawcoin int, xp int, sort int, steps jsonb)
on conflict (key) do update set title = excluded.title, subtitle = excluded.subtitle, description = excluded.description,
    species = excluded.species, tags = excluded.tags, emoji = excluded.emoji, tint = excluded.tint, badge_key = excluded.badge_key,
    pawcoin = excluded.pawcoin, xp = excluded.xp, sort = excluded.sort, steps = excluded.steps;
