-- Görev Merkezi içerik: Günün Bilgisi kartları (ilk 32). Kaynaklı, genel ve temkinli bilgi; her kart veterinere danışmayı önerir.
-- 🔴 vet_reviewed = false: herkese açık yayından önce bir veterinerin okuması gerekir (CLAUDE.md 12.1). İçerik değişince bu dosyayı güncelle.
insert into public.lessons (id, title, summary, body, tip, species, category, read_minutes, emoji, tint, source, sort)
select x.id, x.title, x.summary, x.body, x.tip, x.species, x.category, x.read_minutes, x.emoji, x.tint, x.source, x.sort
from jsonb_to_recordset($j$[
{"id":"sicak-hava-yuruyus","sort":1,"species":["dog"],"category":"hareket","read_minutes":3,"emoji":"☀️","tint":"#FBEFD3",
 "title":"Sıcak havada yürüyüş için en uygun saatler",
 "summary":"Asfalt, havadan çok daha sıcak olabilir. Yürüyüşü sabah erken ya da akşam serinliğinde yap.",
 "body":[{"p":"Güneş altındaki asfalt ve beton, hava sıcaklığından 20–30 °C daha sıcak olabilir; bu da patilerde yanığa yol açabilir."},
         {"h":"7 saniye testi","p":"Elinin tersini 7 saniye yere bastır. Rahatsız oluyorsan köpeğin patileri için de fazla sıcaktır."},
         {"h":"Planlama","p":"Yaz aylarında yürüyüşleri güneş doğduktan sonraki ilk saatlere ve güneş battıktan sonrasına kaydır. Gölgeli rotaları ve çimenli alanları tercih et, yanında su taşı."},
         {"h":"Sıcak çarpması belirtileri","p":"Aşırı soluma, yoğun salya, sendeleme, kusma ya da dilde koyulaşma görürsen köpeği hemen gölgeye al, serin (buz gibi değil) suyla ıslat ve veterinerini ara."}],
 "tip":"Kısa burunlu ırklar (pug, bulldog) sıcağa çok daha hassastır; onlar için yürüyüşleri kısa tut.",
 "source":"RSPCA, AVMA sıcak hava rehberleri"},
{"id":"su-tuketimi","sort":2,"species":null,"category":"bakim","read_minutes":2,"emoji":"💧","tint":"#DFF3EA",
 "title":"Su tüketimi neden önemli?",
 "summary":"Taze su böbreklerin ve sindirimin sağlığı için şart. Kabı her gün yıka ve tazele.",
 "body":[{"p":"Kediler ve köpekler vücut ağırlıklarına göre her gün belirli miktarda su içmelidir; kaba bir ölçü kilogram başına yaklaşık 50 ml'dir. Yaş mama yiyenler sudan daha az içebilir."},
         {"h":"Temiz kap","p":"Bekleyen suda bakteri ve biyofilm oluşur; hayvan suyu bu yüzden reddedebilir. Kabı her gün yıka, suyu tazele."},
         {"h":"Ne zaman dikkat etmeli?","p":"Su içmede ani artış ya da azalma; şeker hastalığı, böbrek ve hormon sorunlarının ilk işareti olabilir. Böyle bir değişiklik fark edersen veterinerine danış."}],
 "tip":"Kediler suyu mama kabından uzakta daha çok içer. Evde birkaç farklı noktaya su koymayı dene.",
 "source":"Cornell Feline Health Center, AKC"},
{"id":"yeni-ev-adaptasyon","sort":3,"species":null,"category":"yeni","read_minutes":3,"emoji":"🏡","tint":"#F3EBDD",
 "title":"Yeni evde adaptasyon ipuçları",
 "summary":"Yeni bir ev, hayvan için büyük bir değişiklik. Güvenli bir oda ve sabit bir rutin uyumu hızlandırır.",
 "body":[{"h":"Güvenli oda","p":"İlk günlerde yatağı, suyu, maması ve (kedi için) kum kabı olan sakin bir oda hazırla. Evin geri kalanını hayvan kendini hazır hissettikçe keşfetsin."},
         {"h":"Rutin","p":"Mama, yürüyüş ve uyku saatlerini her gün aynı tutmak belirsizliği azaltır."},
         {"h":"Sabır","p":"Saklanma, iştahsızlık ya da gece huzursuzluğu ilk günlerde normaldir. Hayvanı zorlamadan, sakin bir sesle yanında ol. İki üç günden uzun süren iştahsızlıkta veterinere danış."}],
 "tip":"Eski evden getirdiğin bir battaniye ya da oyuncak, tanıdık koku sayesinde güven verir.",
 "source":"iCatCare, RSPCA"},
{"id":"zehirli-yiyecekler-kopek","sort":4,"species":["dog"],"category":"saglik","read_minutes":2,"emoji":"🍇","tint":"#F9E1E8",
 "title":"Köpekler için tehlikeli yiyecekler",
 "summary":"Üzüm, çikolata, ksilitol, soğan ve sarımsak köpekler için zehirlidir.",
 "body":[{"h":"Üzüm ve kuru üzüm","p":"Küçük miktarlar bile bazı köpeklerde böbrek yetmezliğine yol açabilir."},
         {"h":"Çikolata","p":"İçindeki teobromin kalp ve sinir sistemini etkiler; bitter çikolata en tehlikelisidir."},
         {"h":"Ksilitol","p":"Şekersiz sakız ve bazı fıstık ezmelerindeki bu tatlandırıcı, kan şekerini tehlikeli biçimde düşürür."},
         {"h":"Soğan, sarımsak, makadamya","p":"Soğan ve sarımsak kansızlığa, makadamya fıstığı halsizlik ve titremeye yol açabilir."},
         {"p":"Köpeğin bunlardan birini yediğinden şüpheleniyorsan belirti beklemeden veterinerini ara."}],
 "tip":"Sofradan artan yemekleri köpeğe vermek yerine ona özel atıştırmalık kullan.",
 "source":"ASPCA Animal Poison Control Center"},
{"id":"zehirli-bitkiler-kedi","sort":5,"species":["cat"],"category":"saglik","read_minutes":2,"emoji":"🌷","tint":"#F9E1E8",
 "title":"Kediler için tehlikeli bitkiler",
 "summary":"Zambak kediler için çok zehirlidir; polenini yalamak bile böbreklere zarar verebilir.",
 "body":[{"h":"Zambak","p":"Lilium ve Hemerocallis türleri kedilerde akut böbrek yetmezliğine yol açabilir. Evde bu bitkileri hiç bulundurmamak en güvenlisidir."},
         {"h":"Diğer bitkiler","p":"Difenbahya, atatürk çiçeği (poinsettia) ve bazı sukulentler ağızda tahriş ve kusmaya yol açabilir."},
         {"p":"Kedinin zehirli olabilecek bir bitkiyi çiğnediğini görürsen bitkinin adını not al ve hemen veterinerini ara."}],
 "tip":"Kediler yeşillik çiğnemeyi sever; onlara özel kedi otu yetiştirmek ilgilerini güvenli bir yere yönlendirir.",
 "source":"ASPCA, iCatCare"},
{"id":"dis-bakimi","sort":6,"species":null,"category":"saglik","read_minutes":3,"emoji":"🦷","tint":"#DFF3EA",
 "title":"Diş bakımı: küçük alışkanlık, büyük fark",
 "summary":"Diş eti hastalığı yetişkin kedi ve köpeklerde çok yaygındır. Düzenli fırçalama en etkili önlemdir.",
 "body":[{"p":"Kedi ve köpeklerin çoğunda üç yaşına kadar bir ölçüde diş eti hastalığı gelişir. Ağız kokusu, kızarık diş eti ve tek taraflı çiğneme ilk işaretlerdir."},
         {"h":"Fırçalama","p":"Hayvanlara özel diş macunu kullan; insan macunu yutulduğunda zararlı olabilir. Önce parmağınla diş etine dokunmaya alıştır, sonra kısa sürelerle fırçaya geç."},
         {"h":"Kontrol","p":"Yıllık sağlık kontrolünde dişlere de baktır; gerekirse veterinerin diş taşı temizliği önerebilir."}],
 "tip":"Her gün 30 saniye bile, haftada bir uzun fırçalamadan daha etkilidir.",
 "source":"AAHA Dental Care Guidelines, AVMA"},
{"id":"asi-takvimi-kopek","sort":7,"species":["dog"],"category":"saglik","read_minutes":3,"emoji":"💉","tint":"#FCE6DF",
 "title":"Köpeklerde temel aşılar",
 "summary":"Karma aşı ve kuduz aşısı her köpek için temel aşılardır. Yavrularda aşı serisi 16 haftalığa kadar sürer.",
 "body":[{"h":"Temel aşılar","p":"Gençlik hastalığı (distemper), parvovirüs, adenovirüs ve kuduz, dünya genelinde her köpeğe önerilen temel aşılardır. Türkiye'de kuduz aşısı yasal olarak zorunludur."},
         {"h":"Yavrularda","p":"Aşılar genellikle 6–8 haftalıkken başlar, 16 haftalık olana kadar birkaç hafta arayla tekrarlanır. Seri bitmeden yavruyu kalabalık köpek alanlarına götürme."},
         {"h":"Hatırlatmalar","p":"Rapel aşıların zamanı aşıya ve yaşam tarzına göre değişir; takvimi veterinerinle birlikte belirle ve Moffi'deki aşı kaydına ekle."}],
 "tip":"Aşı kartının fotoğrafını Moffi'deki sağlık belgelerine yüklersen veteriner değiştirdiğinde kaybolmaz.",
 "source":"WSAVA Aşılama Kılavuzu"},
{"id":"asi-takvimi-kedi","sort":8,"species":["cat"],"category":"saglik","read_minutes":3,"emoji":"💉","tint":"#FCE6DF",
 "title":"Kedilerde temel aşılar",
 "summary":"Panlökopeni, herpes ve kalisi virüsüne karşı karma aşı her kediye önerilir; ev kedileri de dahil.",
 "body":[{"h":"Temel aşılar","p":"Kedi panlökopenisi, kedi herpes virüsü ve kalisi virüsü dünya genelinde temel aşılardır. Kuduz aşısı Türkiye'de yasal olarak zorunludur."},
         {"h":"Ev kedileri","p":"Hiç dışarı çıkmayan kediler de ayakkabı ve kıyafetle eve taşınan virüslerle karşılaşabilir; temel aşıları atlama."},
         {"h":"Yavrularda","p":"Seri genellikle 6–8 haftalıkken başlar ve 16 haftalığa kadar sürer. Takvimi veterinerinle belirle."}],
 "tip":"Aşı sonrası bir gün kadar halsizlik normaldir; yüzde şişlik ya da nefes darlığı olursa hemen veterinere git.",
 "source":"WSAVA Aşılama Kılavuzu, iCatCare"},
{"id":"parazit-korumasi","sort":9,"species":null,"category":"saglik","read_minutes":2,"emoji":"🛡️","tint":"#DFF3EA",
 "title":"İç ve dış parazitlere karşı düzenli koruma",
 "summary":"Pire, kene ve bağırsak kurtları hem hayvanın hem de evdekilerin sağlığını etkiler.",
 "body":[{"p":"Dış parazitler (pire, kene) kaşıntı ve kan yoluyla bulaşan hastalıklara; iç parazitler kilo kaybı ve ishale yol açabilir. Bazıları insanlara da geçebilir."},
         {"h":"Ne sıklıkla?","p":"Koruma sıklığı hayvanın yaşına, yaşam tarzına ve bölgeye göre değişir. Ayda bir ya da üç ayda bir gibi bir plan için veterinerine danış."},
         {"p":"Uyguladığın her ilacı Moffi'deki parazit kaydına eklersen bir sonraki dozun zamanı sana hatırlatılır."}],
 "tip":"Köpek ilaçlarının bazıları kediler için zehirlidir. Kediye asla köpek pire ilacı uygulama.",
 "source":"ESCCAP"},
{"id":"kilo-takibi","sort":10,"species":null,"category":"saglik","read_minutes":3,"emoji":"⚖️","tint":"#F3EBDD",
 "title":"İdeal kilo nasıl anlaşılır?",
 "summary":"Kaburgalar elle kolayca hissedilmeli ama gözle görünmemeli. Haftalık tartı erken uyarı verir.",
 "body":[{"h":"Vücut kondisyonu","p":"Elini yan tarafına koy: kaburgaları ince bir yağ tabakasının altında kolayca hissedebilmelisin. Yukarıdan bakınca bel çizgisi belirgin olmalı."},
         {"h":"Evde tartı","p":"Önce kendini tart, sonra hayvanı kucağına alıp tekrar tart; aradaki fark hayvanın kilosudur."},
         {"p":"Kilodaki yavaş artış eklem sorunlarını, açıklanamayan kayıp ise bir hastalığı işaret edebilir. Değişimi fark edersen veterinerine danış."}],
 "tip":"Ödül mamalarını günlük mamadan düşmeyi unutma; küçük ödüller hızla birikir.",
 "source":"WSAVA Vücut Kondisyon Skoru"},
{"id":"tirnak-kesimi","sort":11,"species":null,"category":"bakim","read_minutes":2,"emoji":"✂️","tint":"#F3EBDD",
 "title":"Tırnak kesiminde dikkat edilecekler",
 "summary":"Uzun tırnaklar yürüyüşü bozar. Küçük parçalar halinde, damara gelmeden kes.",
 "body":[{"p":"Yürürken yere tıkırdayan tırnaklar uzamış demektir; zamanla duruşu ve eklemleri etkileyebilir."},
         {"h":"Nasıl?","p":"Açık renkli tırnaklarda pembe damar görünür; ondan birkaç milimetre önce kes. Koyu tırnaklarda küçük parçalar al ve kesik yüzeyin ortasında koyu bir nokta belirince dur."},
         {"p":"Kanarsa temiz bir bezle bastır. Emin değilsen ilk kesimi veterinerinde ya da bakım uzmanında izle."}],
 "tip":"Her kesimden sonra küçük bir ödül vermek, işlemi zamanla keyifli bir rutine çevirir.",
 "source":"RSPCA, AKC"},
{"id":"kedi-kum-kabi","sort":12,"species":["cat"],"category":"bakim","read_minutes":2,"emoji":"🪣","tint":"#F3EBDD",
 "title":"Kum kabı düzeni",
 "summary":"Kedi sayısından bir fazla kum kabı, sessiz bir köşe ve her gün temizlik.",
 "body":[{"h":"Sayı ve yer","p":"Genel kural kedi sayısının bir fazlası kadar kum kabıdır. Kapları sessiz, kolay ulaşılan ve mama kabından uzak yerlere koy."},
         {"h":"Temizlik","p":"Dışkıyı her gün al; kabı haftada bir yıka. Kokulu kumlar ve kapaklı kaplar bazı kedileri rahatsız edebilir."},
         {"p":"Kum kabı dışına yapma çoğu zaman bir sağlık sorununun ya da stresin işaretidir. Ani değişimde veterinerine danış."}],
 "tip":"Kum değiştirirken eskisini yavaş yavaş yenisiyle karıştır.",
 "source":"iCatCare, AAFP"},
{"id":"kedi-tirmalama","sort":13,"species":["cat"],"category":"egitim","read_minutes":2,"emoji":"🪵","tint":"#F3EBDD",
 "title":"Tırmalama bir ihtiyaçtır",
 "summary":"Kediler tırmalayarak tırnak bakımı yapar ve koku bırakır. Doğru yer sunarsan mobilya kurtulur.",
 "body":[{"p":"Tırmalamak kedi için tırnak bakımı, esneme ve iz bırakma yoludur; engellemek yerine yönlendirmek gerekir."},
         {"h":"Doğru tırmalama yeri","p":"Sağlam, devrilmeyen ve kedinin boyu uzandığında ulaşabileceği yükseklikte olsun. Bazı kediler yatay, bazıları dikey yüzeyleri sever."},
         {"h":"Konum","p":"Uyku yerinin yakınına ve kedinin tırmaladığı mobilyanın önüne koy. Kullandığında ödül ver."}],
 "tip":"Tırmalama tahtasına biraz kedi otu sürmek ilgiyi artırır.",
 "source":"iCatCare"},
{"id":"kedi-oyun","sort":14,"species":["cat"],"category":"hareket","read_minutes":2,"emoji":"🧶","tint":"#FCE6DF",
 "title":"Kediyle oyun: avı taklit et",
 "summary":"Kısa ve sık oyunlar en iyisi. Oyunu bir 'yakalama' ve küçük bir ödülle bitir.",
 "body":[{"p":"Kediler doğal avcıdır: izleme, gizlenme, sıçrama ve yakalama. Olta oyuncağıyla bu sırayı taklit etmek hem bedeni hem zihni yorar."},
         {"h":"Süre","p":"Günde birkaç kez 5–10 dakikalık oyunlar, tek uzun oyundan daha etkilidir."},
         {"h":"Bitiriş","p":"Oyunun sonunda kedinin oyuncağı yakalamasına izin ver ve küçük bir ödül ver; avın tamamlandığını hissetsin."}],
 "tip":"Lazer ışığı kullanıyorsan oyunu mutlaka yakalanabilen bir oyuncakla bitir.",
 "source":"iCatCare"},
{"id":"yavru-sosyallesme","sort":15,"species":["dog"],"category":"egitim","read_minutes":3,"emoji":"🐶","tint":"#FCE6DF",
 "title":"Yavru köpeklerde sosyalleşme penceresi",
 "summary":"3 ile 14 haftalık arası, yavrunun dünyayı tanıdığı kritik dönem. Güvenli ve olumlu deneyimler sun.",
 "body":[{"p":"Bu dönemde karşılaştığı insanlar, sesler, yüzeyler ve hayvanlar ileride neye korkusuzca yaklaşacağını belirler."},
         {"h":"Güvenli yollar","p":"Aşı serisi tamamlanmadan kalabalık köpek alanlarından kaçın; ama aşılı, sağlıklı köpeklerle tanıştırmak, kucakta şehir gezmek ve evde farklı sesler dinletmek güvenlidir."},
         {"h":"Olumlu kal","p":"Her yeni deneyimi ödülle eşleştir; yavru korkarsa zorlamadan mesafeyi artır."}],
 "tip":"Yavru eğitim sınıfları hem sosyalleşme hem temel eğitim için iyi bir başlangıçtır.",
 "source":"AVSAB Yavru Sosyalleşme Bildirgesi"},
{"id":"mikrocip-kunye","sort":16,"species":null,"category":"saglik","read_minutes":2,"emoji":"🏷️","tint":"#DFF3EA",
 "title":"Mikroçip ve künye: kaybolursa geri dönüş yolu",
 "summary":"Türkiye'de kedi ve köpekler için mikroçip ve PETVET kaydı zorunludur. Künye ise en hızlı iletişim yoludur.",
 "body":[{"p":"Mikroçip, hayvanı bulan kişinin bir veteriner ya da belediye aracılığıyla sana ulaşmasını sağlar. Kayıttaki telefonun güncel olduğundan emin ol."},
         {"h":"Künye","p":"Tasmadaki künye, hayvanı bulan kişinin seni hemen aramasını sağlar. Moffi'nin QR künyesi telefonunu göstermeden mesaj atılmasına izin verir."},
         {"p":"Taşınma ya da numara değişikliğinde hem çip kaydını hem künyeyi güncelle."}],
 "tip":"Pasaportunda çip numarası eksikse ekle; kayıp ilanında bu bilgi işe yarar.",
 "source":"T.C. Tarım ve Orman Bakanlığı (PETVET)"},
{"id":"acil-belirtiler","sort":17,"species":null,"category":"saglik","read_minutes":3,"emoji":"🚨","tint":"#F9E1E8",
 "title":"Beklemeden veterinere gidilmesi gereken durumlar",
 "summary":"Nefes darlığı, şişkin karın, tekrarlayan kusma ve bilinç bulanıklığı acil durumdur.",
 "body":[{"p":"Bazı belirtiler saatler içinde ağırlaşabilir; bunlarda sabahı bekleme."},
         {"h":"Hemen git","p":"Nefes almakta zorlanma, solgun ya da morarmış diş eti, şişmiş ve sert karın (özellikle göğsü derin köpeklerde), tekrarlayan kusma ya da kanlı ishal, nöbet, zehirli bir madde yutma, idrar yapamama (özellikle erkek kedilerde)."},
         {"p":"Gitmeden önce veterinerini ara; yolda olduğunu haber vermek hazırlık için zaman kazandırır."}],
 "tip":"En yakın 7/24 açık kliniğin numarasını şimdiden telefonuna kaydet.",
 "source":"AVMA, VCA Animal Hospitals"},
{"id":"ilk-yardim-cantasi","sort":18,"species":null,"category":"saglik","read_minutes":2,"emoji":"🧰","tint":"#F3EBDD",
 "title":"Evde bulunması gereken ilk yardım çantası",
 "summary":"Gazlı bez, elastik bandaj, eldiven, makas ve veterinerinin numarası hazır olsun.",
 "body":[{"h":"Çantada","p":"Steril gazlı bez, elastik bandaj, tek kullanımlık eldiven, küt uçlu makas, cımbız, temiz havlu, ağız bağı ya da yumuşak tasma ve dijital termometre."},
         {"h":"Bilgiler","p":"Veterinerinin ve en yakın acil kliniğin numarası, hayvanın aşı ve ilaç listesi."},
         {"p":"Çanta yalnızca ilk müdahale içindir; ciddi bir yaralanmada en kısa sürede veterinere git."}],
 "tip":"Moffi'deki acil durum bilgisi, künyeyi okutan kişinin de sana ulaşmasını sağlar.",
 "source":"AVMA Pet First Aid"},
{"id":"kis-yuruyus","sort":19,"species":["dog"],"category":"hareket","read_minutes":2,"emoji":"❄️","tint":"#F3EBDD",
 "title":"Soğuk havada yürüyüş",
 "summary":"Yol tuzu ve buz patileri tahriş eder. Yürüyüş sonrası patileri sil.",
 "body":[{"p":"Kısa tüylü, küçük ve yaşlı köpekler soğuktan daha çabuk etkilenir; yürüyüşü kısalt ve gerekiyorsa mont kullan."},
         {"h":"Pati bakımı","p":"Yollara dökülen tuz ve kimyasallar patilerde çatlak yapabilir. Eve dönünce patileri ılık suyla silip kurula."},
         {"p":"Titreme, yavaşlama ya da patisini kaldırarak yürüme, eve dönme zamanının işaretidir."}],
 "tip":"Parmak arasındaki uzun tüyleri kısa tutmak buz topaklarının oluşmasını önler.",
 "source":"AKC, RSPCA"},
{"id":"yasli-hayvan","sort":20,"species":null,"category":"saglik","read_minutes":3,"emoji":"🧓","tint":"#F3EBDD",
 "title":"Yaşlanan dostun ihtiyaçları",
 "summary":"Yaşlı hayvanlarda yılda iki sağlık kontrolü, eklem dostu düzen ve kısa ama sık hareket önerilir.",
 "body":[{"p":"Kediler ve köpekler genellikle 7–10 yaşından sonra yaşlı kabul edilir; büyük ırk köpeklerde bu daha erken başlar."},
         {"h":"Kontroller","p":"Böbrek, tiroit ve eklem sorunları sinsice ilerleyebilir; yılda iki kontrol ve kan tahlili erken teşhis sağlar."},
         {"h":"Evde","p":"Kaymayan zemin, alçak giriş yerleri ve rahat bir yatak eklemleri korur. Uzun yürüyüş yerine kısa ve sık yürüyüş tercih et."}],
 "tip":"Merdiven çıkmakta zorlanma, sertlik ve isteksizlik ağrı belirtisi olabilir; 'yaşlılık' deyip geçme.",
 "source":"AAHA Senior Care Guidelines"},
{"id":"kisirlastirma","sort":21,"species":null,"category":"saglik","read_minutes":2,"emoji":"🩺","tint":"#DFF3EA",
 "title":"Kısırlaştırma hakkında bilinmesi gerekenler",
 "summary":"İstenmeyen yavruları önler ve bazı hastalık risklerini azaltır. Zamanlamayı veterinerinle konuş.",
 "body":[{"p":"Kısırlaştırma, istenmeyen yavruları ve bazı üreme organı hastalıklarını önler; sokak hayvanı sayısının artmasının da önüne geçer."},
         {"h":"Zamanlama","p":"Uygun yaş türe, ırka ve büyüklüğe göre değişir; özellikle büyük ırk köpeklerde veterinerinle birlikte karar ver."},
         {"p":"Ameliyat sonrası iştah ve kilo değişebilir; mama miktarını veterinerinin önerisiyle ayarla."}],
 "tip":"Ameliyat sonrası birkaç gün yalama ve zıplamayı engellemek iyileşmeyi hızlandırır.",
 "source":"WSAVA, AVMA"},
{"id":"stres-belirtileri-kopek","sort":22,"species":["dog"],"category":"egitim","read_minutes":2,"emoji":"🐕","tint":"#FCE6DF",
 "title":"Köpeğin 'rahatsızım' deme yolları",
 "summary":"Esneme, dudak yalama, gözünün beyazını gösterme ve kuyruğunu kısma stres işaretleridir.",
 "body":[{"p":"Köpekler hırlamadan önce çok sayıda küçük işaretle rahatsızlığını anlatır."},
         {"h":"Erken işaretler","p":"Esneme, dudak yalama, başını çevirme, gözün beyazının görünmesi (balina gözü), kuyruğun kısılması ve donup kalma."},
         {"p":"Bu işaretleri gördüğünde durumu sakinleştir ve mesafeyi artır. Hırlamayı cezalandırmak uyarıyı ortadan kaldırır ama korkuyu değil."}],
 "tip":"Çocuklara köpeğin yanından sessizce uzaklaşmayı öğretmek en etkili ısırık önlemidir.",
 "source":"AVSAB, ASPCA"},
{"id":"stres-belirtileri-kedi","sort":23,"species":["cat"],"category":"egitim","read_minutes":2,"emoji":"🐈","tint":"#FCE6DF",
 "title":"Kedide stres nasıl anlaşılır?",
 "summary":"Saklanma, aşırı yalanma, iştah ve kum kabı alışkanlığındaki değişiklikler stresin işaretidir.",
 "body":[{"p":"Kediler stresini çoğu zaman sessizce gösterir. Taşınma, yeni bir hayvan ya da ev içi düzen değişikliği tetikleyebilir."},
         {"h":"İşaretler","p":"Uzun süre saklanma, tüyün bir bölgesini sürekli yalama, iştahsızlık, kum kabı dışına yapma ve kendini geri çekme."},
         {"p":"Saklanabileceği yüksek yerler ve sabit bir rutin rahatlatır. Belirtiler sürerse veterinerine danış; bazıları bir hastalığı da gösterebilir."}],
 "tip":"Kedinin kaçabileceği bir yer olması, yeni durumlara alışmasını kolaylaştırır.",
 "source":"iCatCare, International Society of Feline Medicine"},
{"id":"mama-gecisi","sort":24,"species":null,"category":"bakim","read_minutes":2,"emoji":"🥣","tint":"#DFF3EA",
 "title":"Mama değiştirirken yavaş geçiş",
 "summary":"Yeni mamaya 7–10 günde, eskisiyle karıştırarak geç. Ani değişim ishale yol açabilir.",
 "body":[{"p":"Sindirim sistemi ani değişime hazır değildir; bu yüzden yeni mamayı adım adım artır."},
         {"h":"Örnek plan","p":"İlk 2–3 gün dörtte bir yeni mama, sonraki 2–3 gün yarı yarıya, ardından dörtte üç yeni mama ve sonunda tamamen yeni mama."},
         {"p":"Geçiş sırasında kusma ya da birkaç günden uzun süren ishal olursa geçişi durdur ve veterinerine danış."}],
 "tip":"Mamayı paketteki tablodan değil, hayvanın kilosu ve hareketine göre veterinerinle ayarla.",
 "source":"WSAVA Beslenme Kılavuzu"},
{"id":"odul-egitimi","sort":25,"species":null,"category":"egitim","read_minutes":2,"emoji":"🎯","tint":"#FCE6DF",
 "title":"Ödülle eğitimin püf noktaları",
 "summary":"Doğru davranıştan hemen sonra, birkaç saniye içinde ödül ver. Kısa ve sık seanslar yap.",
 "body":[{"p":"Hayvanlar bir davranışı, ardından gelen sonuçla ilişkilendirir. Ödül birkaç saniye gecikirse neyin ödüllendirildiği anlaşılmaz."},
         {"h":"Seans süresi","p":"Günde birkaç kez 3–5 dakikalık seanslar, uzun ve yorucu seanslardan daha verimlidir."},
         {"p":"Ceza korku ve güven kaybı yaratır; istenmeyen davranışı görmezden gelip istenen davranışı ödüllendirmek daha kalıcı sonuç verir."}],
 "tip":"Ödülü küçük tut; bezelye büyüklüğünde bir parça yeterlidir.",
 "source":"AVSAB Hayvan Eğitimi Bildirgesi"},
{"id":"tuy-bakimi","sort":26,"species":null,"category":"bakim","read_minutes":2,"emoji":"🪮","tint":"#F3EBDD",
 "title":"Tüy bakımı ve tarama",
 "summary":"Düzenli tarama düğümleri önler, deriyi kontrol etme fırsatı verir.",
 "body":[{"p":"Uzun tüylü hayvanlar her gün, kısa tüylüler haftada bir iki kez taranmalıdır. Tüy dökme mevsiminde sıklığı artır."},
         {"h":"Kontrol","p":"Tarama sırasında deride kızarıklık, kepek, şişlik ya da pire pisliği olup olmadığına bak."},
         {"p":"Keçeleşmiş tüyleri makasla kesmek deriyi yaralayabilir; bunun için bakım uzmanına başvur."}],
 "tip":"Kısa ve ödüllü tarama seansları tarağı sevilen bir an haline getirir.",
 "source":"RSPCA"},
{"id":"araba-yolculugu","sort":27,"species":null,"category":"yeni","read_minutes":2,"emoji":"🚗","tint":"#F3EBDD",
 "title":"Arabada güvenli yolculuk",
 "summary":"Kafes ya da emniyet kemerine bağlı koşum kullan. Hayvanı arabada asla tek bırakma.",
 "body":[{"p":"Serbest dolaşan hayvan ani frende yaralanabilir ve sürücünün dikkatini dağıtır. Kediler kafeste, köpekler kafeste ya da emniyet kemerine takılan koşumla seyahat etmelidir."},
         {"h":"Sıcak araba","p":"Ilık bir günde bile kapalı arabanın içi dakikalar içinde tehlikeli derecede ısınır. Pencere aralık bile olsa hayvanı arabada bırakma."},
         {"p":"Uzun yolda iki saatte bir mola ver, su sun."}],
 "tip":"Kafesi evde açık bırakıp içine yatak koymak, onu korkulan bir yer olmaktan çıkarır.",
 "source":"AVMA"},
{"id":"havai-fisek","sort":28,"species":null,"category":"egitim","read_minutes":2,"emoji":"🎆","tint":"#F9E1E8",
 "title":"Havai fişek ve gök gürültüsü korkusu",
 "summary":"Sığınabileceği sessiz bir köşe hazırla, korkusu için cezalandırma.",
 "body":[{"p":"Yüksek sesler pek çok hayvanda yoğun korku yaratır; kaçma sırasında kaybolma riski artar."},
         {"h":"Hazırlık","p":"Perdeleri kapat, sakin bir müzik aç, hayvanın saklanabileceği bir yer hazırla. Kapı ve pencerelerin kapalı olduğundan emin ol."},
         {"p":"Korkan hayvanı teselli etmek korkuyu artırmaz; sakin kal. Şiddetli korkuda önceden veterinerinle konuş."}],
 "tip":"Yılbaşı gibi bilinen gecelerden önce künye ve çip bilgilerini kontrol et.",
 "source":"RSPCA"},
{"id":"kedi-su-icme","sort":29,"species":["cat"],"category":"bakim","read_minutes":2,"emoji":"⛲","tint":"#DFF3EA",
 "title":"Kediye daha çok su içirmenin yolları",
 "summary":"Geniş kaplar, mamadan uzak su noktaları ve yaş mama kedinin su alımını artırır.",
 "body":[{"p":"Kediler doğal olarak az su içer; bu da idrar yolu sorunlarına zemin hazırlayabilir."},
         {"h":"Pratik yollar","p":"Bıyıklarının değmeyeceği geniş ve sığ kaplar kullan, suyu mama kabından uzak birkaç noktaya koy. Bazı kediler akan suyu sever; su çeşmesi deneyebilirsin."},
         {"p":"Yaş mama da su alımına katkı sağlar. Tuvalete sık gidip az idrar yapma acil bir durum olabilir; hemen veterinere git."}],
 "tip":"Seramik ya da cam kaplar, plastik kaplardan daha az koku tutar.",
 "source":"iCatCare, Cornell Feline Health Center"},
{"id":"koklama-yuruyusu","sort":30,"species":["dog"],"category":"hareket","read_minutes":2,"emoji":"👃","tint":"#DFF3EA",
 "title":"Koklama yürüyüşü neden önemli?",
 "summary":"Köpekler dünyayı burnuyla okur. Koklamaya zaman tanımak stresi azaltır ve zihni yorar.",
 "body":[{"p":"Köpeğin koku alma duyusu insandan kat kat güçlüdür; koklamak onun için haber okumak gibidir."},
         {"p":"Araştırmalar, koklamaya fırsat bulan köpeklerin daha iyimser davrandığını gösteriyor. Hızlı ve düz bir yürüyüş yerine arada koklama molaları vermek yürüyüşü daha doyurucu yapar."},
         {"h":"Dene","p":"Haftada bir yürüyüşü 'koklama yürüyüşü' yap: rotayı köpek seçsin, acele etme."}],
 "tip":"Evde ödülleri bir havlunun kıvrımlarına saklamak da güzel bir koklama oyunudur.",
 "source":"Duranton & Horowitz (2019), Applied Animal Behaviour Science"},
{"id":"kene-kontrolu","sort":31,"species":["dog"],"category":"saglik","read_minutes":2,"emoji":"🕷️","tint":"#F9E1E8",
 "title":"Yürüyüş sonrası kene kontrolü",
 "summary":"Çimenli alanlardan sonra kulak, koltuk altı ve parmak aralarını kontrol et.",
 "body":[{"p":"Keneler kan yoluyla hastalık taşıyabilir; ne kadar erken çıkarılırsa risk o kadar azalır."},
         {"h":"Nereye bakmalı?","p":"Kulakların içi ve arkası, boyun, koltuk altları, kasıklar ve parmak araları."},
         {"h":"Çıkarma","p":"Keneyi deriye en yakın yerden özel kene cımbızıyla tutup sabit bir hareketle çek; ezme, yağ ya da alkol sürme. Emin değilsen veterinerinde çıkart."}],
 "tip":"Düzenli dış parazit koruması kene riskini önemli ölçüde azaltır.",
 "source":"ESCCAP"},
{"id":"kedi-zenginlestirme","sort":32,"species":["cat"],"category":"egitim","read_minutes":2,"emoji":"🪟","tint":"#F3EBDD",
 "title":"Ev kedisi için zenginleştirme",
 "summary":"Pencere önü, yükseklik ve saklanma yerleri ev kedisinin dünyasını genişletir.",
 "body":[{"p":"Ev kedileri güvendedir ama can sıkıntısı davranış sorunlarına yol açabilir."},
         {"h":"Fikirler","p":"Pencere önüne bir minder, raf ya da kedi ağacıyla dikey alan, karton kutularla saklanma yerleri ve mama bulmacaları."},
         {"p":"Oyuncakları dönüşümlü kullanmak her seferinde yeni gibi hissettirir."}],
 "tip":"Mamanın bir kısmını bulmaca oyuncağıyla vermek doğal arama davranışını destekler.",
 "source":"iCatCare, AAFP Çevresel İhtiyaçlar Kılavuzu"}
]$j$::jsonb) as x(id text, title text, summary text, body jsonb, tip text, species text[], category text, read_minutes int, emoji text, tint text, source text, sort int)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, body = excluded.body, tip = excluded.tip,
    species = excluded.species, category = excluded.category, read_minutes = excluded.read_minutes, emoji = excluded.emoji,
    tint = excluded.tint, source = excluded.source, sort = excluded.sort;
